name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: current
          registry-url: https://registry.npmjs.org
      - run: bash .ci/build.sh
      - run: bash .ci/test.sh
      - run: bash .ci/publishNpm.sh
        env:
          VERSION: ${{ github.ref_name }}
